openapi: 3.0.0
info:
  title: ""
  version: 1.0.0
servers:
- url: /
paths:
  /aaa/api-keys/v3:
    get:
      description: Retrieve all API keys for team members.
      externalDocs:
        url: ""
      operationId: ApiKeysAdminService_GetTeamMembersApiKeys
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetTeamMembersApiKeysResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Get Team Members API Keys
      tags:
      - API Keys Admin Service
    post:
      description: Creates a new API key for the authenticated team.
      externalDocs:
        url: ""
      operationId: ApiKeysService_CreateApiKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Create_Api_Key_Request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateApiKeyResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Create API Key
      tags:
      - API Keys Service
  /aaa/api-keys/v3/list/all:
    get:
      description: Returns all API keys for the authenticated team.
      externalDocs:
        url: ""
      operationId: ApiKeysService_GetApiKeys
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetApiKeysResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Get API Keys
      tags:
      - API Keys Service
  /aaa/api-keys/v3/{key_id}:
    delete:
      description: Deletes the API key with the given ID.
      externalDocs:
        url: ""
      operationId: ApiKeysService_DeleteApiKey
      parameters:
      - description: The unique identifier of the API key to delete.
        explode: false
        in: path
        name: key_id
        required: true
        schema:
          description: The unique identifier of the API key to delete.
          minLength: 0
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteApiKeyResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Delete API Key
      tags:
      - API Keys Service
    get:
      description: Returns the details of the specified API key.
      externalDocs:
        url: ""
      operationId: ApiKeysService_GetApiKey
      parameters:
      - description: Key identifier.
        explode: false
        in: path
        name: key_id
        required: true
        schema:
          description: Key identifier.
          example: my_key_id
          minLength: 0
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetApiKeyResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Get API Key
      tags:
      - API Keys Service
    put:
      description: Updates the specified API key.
      externalDocs:
        url: ""
      operationId: ApiKeysService_UpdateApiKey
      parameters:
      - description: Key identifier.
        explode: false
        in: path
        name: key_id
        required: true
        schema:
          description: Key identifier.
          example: my_key_id
          minLength: 0
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Update_Api_Key_Request"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateApiKeyResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Update API Key
      tags:
      - API Keys Service
  /aaa/send-data-keys/v3:
    get:
      description: Returns all send-data API keys for the authenticated team.
      externalDocs:
        url: ""
      operationId: ApiKeysService_GetSendDataApiKeys
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSendDataApiKeysResponse"
          description: ""
        "400":
          content:
            application/json: {}
          description: Bad Request
        "401":
          content:
            application/json: {}
          description: Unauthorized request
        "500":
          content:
            application/json: {}
          description: Internal server error
      summary: Get "Send Data" API Keys
      tags:
      - API Keys Service
components:
  schemas:
    ApiKeyOwner:
      description: This data structure represents the owner of an API key.
      example:
        user:
          userEmail: test@example.com
          userId: user_123
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        user:
          $ref: "#/components/schemas/ApiKeyUserOwner"
      title: API Key Owner
      type: object
    ApiKeySummary:
      description: This data structure represents summary about an API key including
        its permissions.
      example:
        presets:
        - permissions:
          - logs:read
          - logs:read
          name: my_preset
          id: 1
        - permissions:
          - logs:read
          - logs:read
          name: my_preset
          id: 1
        apiKey:
          owner:
            user:
              userEmail: test@example.com
              userId: user_123
          createdAt: 2000-01-23T04:56:07.000+00:00
          lastActivated: 2000-01-23T04:56:07.000+00:00
          keyName: my_api_key
          id: key_abc123
          isActive: true
        permissions:
        - logs:read
        - logs:read
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        apiKey:
          $ref: "#/components/schemas/v3.ApiKey"
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            example: logs:read
            minLength: 0
            type: string
          minItems: 0
          type: array
        presets:
          description: List of permission presets.
          items:
            $ref: "#/components/schemas/PermissionsPreset"
          minItems: 0
          type: array
      title: API Key Summary
      type: object
    ApiKeyUserOwner:
      description: This data structure represents the user owner of an API key.
      example:
        userEmail: test@example.com
        userId: user_123
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        userEmail:
          description: The user email.
          example: test@example.com
          minLength: 0
          type: string
        userId:
          description: The user id.
          example: user_123
          minLength: 0
          type: string
      title: API Key User Owner
      type: object
    CreateApiKeyRequest.KeyPermissions:
      description: This data structure allows to specify loose permissions and permission
        presets for an API key.
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            example: read_logs
            minLength: 0
            type: string
          minItems: 0
          type: array
        presets:
          description: List of permission presets.
          items:
            description: List of permission presets.
            example: my_preset
            minLength: 0
            type: string
          minItems: 0
          type: array
      title: Key Permissions
      type: object
    CreateApiKeyResponse:
      description: This data structure is the response obtained when creating an API
        key.
      example:
        name: my_api_key
        keyId: my_key_id
        value: my_api_key_value
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        keyId:
          description: Key identifier.
          example: my_key_id
          minLength: 0
          type: string
        name:
          description: Display name.
          example: my_api_key
          minLength: 0
          type: string
        value:
          description: The value.
          example: my_api_key_value
          minLength: 0
          type: string
      title: Create Api Key Response
      type: object
    DeleteApiKeyResponse:
      additionalProperties: false
      description: Response returned after successfully deleting an API key.
      externalDocs:
        url: ""
      type: object
    FilterPathAndValues:
      oneOf:
      - $ref: "#/components/schemas/FilterPathAndValuesFilters"
      - $ref: "#/components/schemas/FilterPathAndValuesMultipleValues"
    FilterPathAndValuesFilters:
      description: This data structure represents a filter path and values
      externalDocs:
        url: ""
      properties:
        filters:
          $ref: "#/components/schemas/Filters"
        path:
          example: test
          minLength: 0
          type: string
      required:
      - filters
      - path
      - values
      title: FilterPathAndValues
      type: object
    FilterPathAndValuesMultipleValues:
      description: This data structure represents a filter path and values
      externalDocs:
        url: ""
      properties:
        multipleValues:
          $ref: "#/components/schemas/MultipleValues"
        path:
          example: test
          minLength: 0
          type: string
      required:
      - multipleValues
      - path
      - values
      title: FilterPathAndValues
      type: object
    Filters:
      description: This data structure represents a filter
      externalDocs:
        url: ""
      properties:
        operator:
          $ref: "#/components/schemas/v3.FilterOperator"
        pathAndValues:
          items:
            $ref: "#/components/schemas/FilterPathAndValues"
          minItems: 0
          type: array
      required:
      - pathAndValues
      title: Filters
      type: object
    GetApiKeyResponse:
      description: This data structure is the response obtained when retrieving an
        API key.
      example:
        keyInfo:
          owner:
            organisationId: organisationId
          name: my_api_key
          active: true
          hashed: true
          accessPolicy: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\"\
            :{\"data-ingest-api-keys:ReadAccessPolicy\":\"grant\",\"data-ingest-api-keys:Manage\"\
            :\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\":\"deny\",\"data-ingest-api-keys:ReadConfig\"\
            :\"grant\"}},\"rules\":[]}"
          id: id
          keyPermissions:
            presets:
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            permissions:
            - permissions
            - permissions
          value: value
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        keyInfo:
          $ref: "#/components/schemas/KeyInfo"
      title: Get Api Key Response
      type: object
    GetApiKeysResponse:
      description: This data structure is the response obtained when retrieving all
        API keys.
      example:
        keys:
        - owner:
            organisationId: organisationId
          name: my_api_key
          active: true
          hashed: true
          accessPolicy: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\"\
            :{\"data-ingest-api-keys:ReadAccessPolicy\":\"grant\",\"data-ingest-api-keys:Manage\"\
            :\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\":\"deny\",\"data-ingest-api-keys:ReadConfig\"\
            :\"grant\"}},\"rules\":[]}"
          id: id
          keyPermissions:
            presets:
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            permissions:
            - permissions
            - permissions
          value: value
        - owner:
            organisationId: organisationId
          name: my_api_key
          active: true
          hashed: true
          accessPolicy: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\"\
            :{\"data-ingest-api-keys:ReadAccessPolicy\":\"grant\",\"data-ingest-api-keys:Manage\"\
            :\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\":\"deny\",\"data-ingest-api-keys:ReadConfig\"\
            :\"grant\"}},\"rules\":[]}"
          id: id
          keyPermissions:
            presets:
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            permissions:
            - permissions
            - permissions
          value: value
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        keys:
          description: The keys.
          items:
            $ref: "#/components/schemas/KeyInfo"
          minItems: 0
          type: array
      title: Get Api Keys Response
      type: object
    GetSendDataApiKeysResponse:
      description: This data structure is the response obtained when retrieving an
        API key.
      example:
        keys:
        - owner:
            organisationId: organisationId
          name: my_api_key
          active: true
          hashed: true
          accessPolicy: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\"\
            :{\"data-ingest-api-keys:ReadAccessPolicy\":\"grant\",\"data-ingest-api-keys:Manage\"\
            :\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\":\"deny\",\"data-ingest-api-keys:ReadConfig\"\
            :\"grant\"}},\"rules\":[]}"
          id: id
          keyPermissions:
            presets:
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            permissions:
            - permissions
            - permissions
          value: value
        - owner:
            organisationId: organisationId
          name: my_api_key
          active: true
          hashed: true
          accessPolicy: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\"\
            :{\"data-ingest-api-keys:ReadAccessPolicy\":\"grant\",\"data-ingest-api-keys:Manage\"\
            :\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\":\"deny\",\"data-ingest-api-keys:ReadConfig\"\
            :\"grant\"}},\"rules\":[]}"
          id: id
          keyPermissions:
            presets:
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            - permissions:
              - read_logs
              - read_logs
              name: my_preset
            permissions:
            - permissions
            - permissions
          value: value
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        keys:
          description: The keys.
          items:
            $ref: "#/components/schemas/KeyInfo"
          minItems: 0
          type: array
      title: Get Api Key Response
      type: object
    GetTeamMembersApiKeysResponse:
      description: This data structure is the response obtained when retrieving team
        members API keys.
      example:
        keys:
        - presets:
          - permissions:
            - logs:read
            - logs:read
            name: my_preset
            id: 1
          - permissions:
            - logs:read
            - logs:read
            name: my_preset
            id: 1
          apiKey:
            owner:
              user:
                userEmail: test@example.com
                userId: user_123
            createdAt: 2000-01-23T04:56:07.000+00:00
            lastActivated: 2000-01-23T04:56:07.000+00:00
            keyName: my_api_key
            id: key_abc123
            isActive: true
          permissions:
          - logs:read
          - logs:read
        - presets:
          - permissions:
            - logs:read
            - logs:read
            name: my_preset
            id: 1
          - permissions:
            - logs:read
            - logs:read
            name: my_preset
            id: 1
          apiKey:
            owner:
              user:
                userEmail: test@example.com
                userId: user_123
            createdAt: 2000-01-23T04:56:07.000+00:00
            lastActivated: 2000-01-23T04:56:07.000+00:00
            keyName: my_api_key
            id: key_abc123
            isActive: true
          permissions:
          - logs:read
          - logs:read
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        keys:
          description: The keys.
          items:
            $ref: "#/components/schemas/ApiKeySummary"
          minItems: 0
          type: array
      title: Get Team Members API Keys Response
      type: object
    KeyInfo:
      description: This data structure represents the information associated with
        an API key.
      example:
        owner:
          organisationId: organisationId
        name: my_api_key
        active: true
        hashed: true
        accessPolicy: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\":{\"\
          data-ingest-api-keys:ReadAccessPolicy\":\"grant\",\"data-ingest-api-keys:Manage\"\
          :\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\":\"deny\",\"data-ingest-api-keys:ReadConfig\"\
          :\"grant\"}},\"rules\":[]}"
        id: id
        keyPermissions:
          presets:
          - permissions:
            - read_logs
            - read_logs
            name: my_preset
          - permissions:
            - read_logs
            - read_logs
            name: my_preset
          permissions:
          - permissions
          - permissions
        value: value
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        accessPolicy:
          description: JSON string representing the access policy for this API key.
            Defines granular permissions for users and groups.
          example: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\":{\"data-ingest-api-keys:ReadAccessPolicy\"\
            :\"grant\",\"data-ingest-api-keys:Manage\":\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\"\
            :\"deny\",\"data-ingest-api-keys:ReadConfig\":\"grant\"}},\"rules\":[]}"
          minLength: 0
          type: string
        active:
          description: Whether this resource is active.
          example: true
          type: boolean
        hashed:
          description: Whether the value is stored as a one-way hash.
          example: true
          type: boolean
        id:
          description: Unique identifier.
          minLength: 0
          type: string
        keyPermissions:
          $ref: "#/components/schemas/KeyInfo.KeyPermissions"
        name:
          description: Display name.
          example: my_api_key
          minLength: 0
          type: string
        owner:
          $ref: "#/components/schemas/Owner"
        value:
          description: The value.
          minLength: 0
          type: string
      title: Key Info
      type: object
    KeyInfo.KeyPermissions:
      description: This data structure represents the permissions on an API key.
      example:
        presets:
        - permissions:
          - read_logs
          - read_logs
          name: my_preset
        - permissions:
          - read_logs
          - read_logs
          name: my_preset
        permissions:
        - permissions
        - permissions
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        permissions:
          description: Permissions.
          items:
            description: Permissions.
            minLength: 0
            type: string
          minItems: 0
          type: array
        presets:
          description: Presets.
          items:
            $ref: "#/components/schemas/PresetInfo"
          minItems: 0
          type: array
      title: Key Permissions
      type: object
    MultipleValues:
      properties:
        matcher:
          $ref: "#/components/schemas/events.v3.FilterMatcher"
        values:
          items:
            minLength: 0
            type: string
          minItems: 0
          type: array
      type: object
    Owner:
      oneOf:
      - $ref: "#/components/schemas/OwnerOrganisationId"
      - $ref: "#/components/schemas/OwnerTeamId"
      - $ref: "#/components/schemas/OwnerUserId"
    OwnerOrganisationId:
      description: Owner.
      example:
        organisationId: organisationId
      externalDocs:
        url: ""
      properties:
        organisationId:
          description: Organisation identifier of the API key owner.
          minLength: 0
          type: string
      required:
      - organisationId
      type: object
    OwnerTeamId:
      description: Owner.
      externalDocs:
        url: ""
      properties:
        teamId:
          description: The team id.
          format: int64
          minimum: 0
          type: integer
      required:
      - teamId
      type: object
    OwnerUserId:
      description: Owner.
      externalDocs:
        url: ""
      properties:
        userId:
          description: User identifier of the API key owner.
          minLength: 0
          type: string
      required:
      - userId
      type: object
    PermissionsPreset:
      description: This data structure represents a preset set of permissions on an
        API key.
      example:
        permissions:
        - logs:read
        - logs:read
        name: my_preset
        id: 1
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        id:
          description: Unique identifier.
          example: 1
          format: int32
          type: integer
        name:
          description: Display name.
          example: my_preset
          minLength: 0
          type: string
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            example: logs:read
            minLength: 0
            type: string
          minItems: 0
          type: array
      title: Permissions Preset
      type: object
    PresetInfo:
      description: This data structure represents a preset set of permissions on an
        API key.
      example:
        permissions:
        - read_logs
        - read_logs
        name: my_preset
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        name:
          description: Display name.
          example: my_preset
          minLength: 0
          type: string
        permissions:
          description: List of permissions.
          items:
            description: List of permissions.
            example: read_logs
            minLength: 0
            type: string
          minItems: 0
          type: array
      title: Preset Info
      type: object
    Presets:
      description: This data structure represents a set of permissions presets on
        an API key.
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        presets:
          description: Presets.
          items:
            description: Presets.
            minLength: 0
            type: string
          minItems: 0
          type: array
      title: Presets
      type: object
    UpdateApiKeyRequest.Permissions:
      description: This data structure represents a set of permissions on an API key.
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        permissions:
          description: List of individual permissions to grant to the API key.
          items:
            description: List of individual permissions to grant to the API key.
            minLength: 0
            type: string
          minItems: 0
          type: array
      title: Permissions
      type: object
    UpdateApiKeyResponse:
      additionalProperties: false
      description: Response returned after successfully updating an API key.
      externalDocs:
        url: ""
      type: object
    events.v3.FilterMatcher:
      enum:
      - FILTER_MATCHER_TEXT_OR_UNSPECIFIED
      - FILTER_MATCHER_REGEXP
      type: string
    v3.ApiKey:
      description: This data structure represents an API key with its metadata.
      example:
        owner:
          user:
            userEmail: test@example.com
            userId: user_123
        createdAt: 2000-01-23T04:56:07.000+00:00
        lastActivated: 2000-01-23T04:56:07.000+00:00
        keyName: my_api_key
        id: key_abc123
        isActive: true
      externalDocs:
        description: Find out more about api keys
        url: https://coralogix.com/docs/user-guides/account-management/api-keys/api-keys/
      properties:
        createdAt:
          description: The timestamp when the API key was created.
          format: date-time
          minLength: 0
          type: string
        id:
          description: Unique identifier.
          example: key_abc123
          minLength: 0
          type: string
        isActive:
          description: Whether this resource is active.
          type: boolean
        keyName:
          description: The key name.
          example: my_api_key
          minLength: 0
          type: string
        lastActivated:
          description: The timestamp when the API key was last activated.
          format: date-time
          minLength: 0
          type: string
        owner:
          $ref: "#/components/schemas/ApiKeyOwner"
      title: API Key
      type: object
    v3.FilterOperator:
      description: Filter operator.
      enum:
      - FILTER_OPERATOR_AND_OR_UNSPECIFIED
      - FILTER_OPERATOR_OR
      type: string
    Create_Api_Key_Request:
      description: This data structure is used to create an API key.
      properties:
        accessPolicy:
          description: JSON string representing the access policy for this API key.
            Defines granular permissions for users and groups.
          example: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\":{\"data-ingest-api-keys:ReadAccessPolicy\"\
            :\"grant\",\"data-ingest-api-keys:Manage\":\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\"\
            :\"deny\",\"data-ingest-api-keys:ReadConfig\":\"grant\"}},\"rules\":[]}"
          minLength: 0
          type: string
        hashed:
          description: Whether the value is stored as a one-way hash.
          example: true
          type: boolean
        keyPermissions:
          $ref: "#/components/schemas/CreateApiKeyRequest.KeyPermissions"
        name:
          description: Display name.
          example: my_api_key
          minLength: 0
          type: string
        owner:
          $ref: "#/components/schemas/Owner"
      title: Create Api Key Request
      type: object
    Update_Api_Key_Request:
      description: This data structure is used to update an API key.
      properties:
        accessPolicy:
          description: "JSON string representing the access policy for this API key.\
            \ Defines granular permissions for users and groups. To delete an existing\
            \ policy, pass an empty string."
          example: "{\"version\":\"2025-01-01\",\"default\":{\"permissions\":{\"data-ingest-api-keys:ReadAccessPolicy\"\
            :\"grant\",\"data-ingest-api-keys:Manage\":\"deny\",\"data-ingest-api-keys:UpdateAccessPolicy\"\
            :\"deny\",\"data-ingest-api-keys:ReadConfig\":\"grant\"}},\"rules\":[]}"
          minLength: 0
          type: string
        isActive:
          description: Whether the API key is active. Set to false to deactivate without
            deleting.
          example: true
          type: boolean
        newName:
          description: New display name for the API key.
          example: my_new_name
          minLength: 0
          type: string
        permissions:
          $ref: "#/components/schemas/UpdateApiKeyRequest.Permissions"
        presets:
          $ref: "#/components/schemas/Presets"
      title: Update Api Key Request
      type: object
